#!/bin/sh

bspc monitor -d '1' '2' '3'

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 2
bspc config window_gap 10
bspc config window_gap_top 30
bspc config split_ratio 0.50

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#7fbbb3"
bspc config normal_border_color         "#4b565c"
bspc config active_border_color         "#4b565c"

#
# Autostart
#

# Bar
sh ~/.config/polybar/launch.sh

# Wallpaper
nitrogen --restore &

# Picom
picom --config ~/.config/picom/picom.conf &

# urxvt &
